import { DashboardLayout } from "@/components/dashboard-layout";
import { ContentSkeleton, NavbarSkeleton } from "@/components/loading/admin";
import { Skeleton } from "@/components/ui/skeleton";
import { getServerSession } from "@/lib/get-session";
import type { Metadata } from "next";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Shaheen's Clinic Dashboard",
  description: "Generated by create next app",
};

async function SessionProvider({ children }: { children: React.ReactNode }) {
  const session = await getServerSession();
  const user = session?.user;

  return <DashboardLayout user={user}>{children}</DashboardLayout>;
}

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Suspense
      fallback={
        <div className="flex items-start gap-4">
          <div className="hidden lg:block w-[296px]">
            <Skeleton className="fixed w-[296px] left-0 top-0 h-full" />
          </div>
          <div className="flex-1">
            <NavbarSkeleton />
            <ContentSkeleton />
          </div>
        </div>
      }
    >
      <SessionProvider>{children}</SessionProvider>
    </Suspense>
  );
}
